In [1]:
%matplotlib inline


What is PyTorch?
================

It’s a Python based scientific computing package targeted at two sets of
audiences:

-  A replacement for numpy to use the power of GPUs
-  a deep learning research platform that provides maximum flexibility
   and speed

Getting Started
---------------

Tensors
^^^^^^^

Tensors are similar to numpy’s ndarrays, with the addition being that
Tensors can also be used on a GPU to accelerate computing.



In [2]:
from __future__ import print_function
import torch

Construct a 5x3 matrix, uninitialized:



In [3]:
x = torch.Tensor(5, 3)
print(x)


-4.4051e+08  4.5674e-41 -4.4051e+08
 4.5674e-41  0.0000e+00  0.0000e+00
 0.0000e+00  0.0000e+00  0.0000e+00
 0.0000e+00  0.0000e+00  0.0000e+00
 0.0000e+00  0.0000e+00  0.0000e+00
[torch.FloatTensor of size 5x3]



Construct a randomly initialized matrix



In [17]:
x = torch.rand(5, 3)
print(x)


 0.4800  0.8764  0.7585
 0.6128  0.5833  0.4394
 0.8694  0.7902  0.8513
 0.9608  0.8869  0.1190
 0.9274  0.4343  0.4610
[torch.FloatTensor of size 5x3]



Get its size



In [5]:
print(x.size())

torch.Size([5, 3])


<div class="alert alert-info"><h4>Note</h4><p>``torch.Size`` is in fact a tuple, so it supports the same operations</p></div>

Operations
^^^^^^^^^^
There are multiple syntaxes for operations. Let's see addition as an example

Addition: syntax 1



In [6]:
y = torch.rand(5, 3)
print(x + y)


 1.1493  1.3134  1.0022
 0.7082  0.6964  0.7750
 0.2276  1.3727  0.6443
 1.1423  1.1984  0.6432
 1.7833  1.2806  1.0940
[torch.FloatTensor of size 5x3]



Addition: syntax 2



In [7]:
print(torch.add(x, y))


 1.1493  1.3134  1.0022
 0.7082  0.6964  0.7750
 0.2276  1.3727  0.6443
 1.1423  1.1984  0.6432
 1.7833  1.2806  1.0940
[torch.FloatTensor of size 5x3]



Addition: giving an output tensor



In [8]:
result = torch.Tensor(5, 3)
torch.add(x, y, out=result)
print(result)


 1.1493  1.3134  1.0022
 0.7082  0.6964  0.7750
 0.2276  1.3727  0.6443
 1.1423  1.1984  0.6432
 1.7833  1.2806  1.0940
[torch.FloatTensor of size 5x3]



Addition: in-place



In [9]:
# adds x to y
y.add_(x)
print(y)


 1.1493  1.3134  1.0022
 0.7082  0.6964  0.7750
 0.2276  1.3727  0.6443
 1.1423  1.1984  0.6432
 1.7833  1.2806  1.0940
[torch.FloatTensor of size 5x3]



<div class="alert alert-info"><h4>Note</h4><p>Any operation that mutates a tensor in-place is post-fixed with an ``_``
    For example: ``x.copy_(y)``, ``x.t_()``, will change ``x``.</p></div>

You can use standard numpy-like indexing with all bells and whistles!



In [18]:

print(x[:, 1])


 0.8764
 0.5833
 0.7902
 0.8869
 0.4343
[torch.FloatTensor of size 5]



In [20]:
x=torch.rand(2,5,3)
x


(0 ,.,.) = 
  0.8340  0.5007  0.4401
  0.0902  0.0002  0.2541
  0.5906  0.8464  0.1461
  0.5508  0.8791  0.9512
  0.2213  0.5248  0.0265

(1 ,.,.) = 
  0.4122  0.9080  0.4619
  0.6878  0.7760  0.7475
  0.5099  0.6807  0.6827
  0.0405  0.6030  0.6675
  0.8395  0.4244  0.2122
[torch.FloatTensor of size 2x5x3]

In [23]:
x[1,2,:]


 0.5099
 0.6807
 0.6827
[torch.FloatTensor of size 3]

Resizing: If you want to resize/reshape tensor, you can use ``torch.view``:



In [35]:
x = torch.randn(4, 4)
y = x.view(16)
z = x.view(-1, 16)  # the size -1 is inferred from other dimensions so that the product is as the start
print(x.size(), y.size(), z.size())

torch.Size([4, 4]) torch.Size([16]) torch.Size([1, 16])


In [36]:
z



Columns 0 to 9 
 1.7788 -0.0386 -1.8017  0.0852 -0.9347  0.5393 -1.0727  0.3240  0.9609  0.4044

Columns 10 to 15 
-1.1582  0.9272 -0.6622  0.7420 -0.0395  1.9329
[torch.FloatTensor of size 1x16]

**Read later:**


  100+ Tensor operations, including transposing, indexing, slicing,
  mathematical operations, linear algebra, random numbers, etc are described
  `here <http://pytorch.org/docs/torch>`_

Numpy Bridge
------------

Converting a torch Tensor to a numpy array and vice versa is a breeze.

The torch Tensor and numpy array will share their underlying memory
locations, and changing one will change the other.

Converting torch Tensor to numpy Array
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^



In [38]:
a = torch.ones(1,5)
print(a)


 1  1  1  1  1
[torch.FloatTensor of size 1x5]



In [39]:
b = a.numpy()
print(b)

[[ 1.  1.  1.  1.  1.]]


See how the numpy array changed in value.



In [40]:
a.add_(1)
print(a)
print(b)


 2  2  2  2  2
[torch.FloatTensor of size 1x5]

[[ 2.  2.  2.  2.  2.]]


Converting numpy Array to torch Tensor  
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^  
See how changing the np array changed the torch Tensor automatically



In [41]:
import numpy as np
a = np.ones(5)
b = torch.from_numpy(a)
np.add(a, 1, out=a)
print(a)
print(b)

[ 2.  2.  2.  2.  2.]

 2
 2
 2
 2
 2
[torch.DoubleTensor of size 5]



All the Tensors on the CPU except a CharTensor support converting to
NumPy and back.

CUDA Tensors
------------

Tensors can be moved onto GPU using the ``.cuda`` function.



In [42]:
# let us run this cell only if CUDA is available
if torch.cuda.is_available():
    x = x.cuda()
    y = y.cuda()
    x + y